### ISSUE TITLE
Assets with _ in their name give an error

### ISSUE THREAD

**Issue by vHanda** [chenenyu/assets_gen#4]
Hi. I have the following assets -

```
Animated_Checkmark.json                  No_Internet_-_Dark_Mode.json.json
Animated_X.json                          No_Orders_Yet.json
Loading_State.json                       No_Pending_Prescriptions.json
No_Internet_Animation_-_Light.json.json  Your_Cart_is_Empty_Animation.json.json
```

I'm running it with the following settings set in the pubspec.yaml file -

```
assets_gen:
  output: generated/assets.dart
  omit_path_levels: 1
  code_style: lowerCamelCase
```

I get the following error - 
```
$ flutter pub run assets_gen build
[INFO] Building...
[INFO] Generating package:medl
Unhandled exception:
RangeError (end): Invalid value: Only valid value is 0: 1
#0      RangeError.checkValidRange (dart:core/errors.dart:363:9)
#1      _StringBase.substring (dart:core-patch/string_patch.dart:400:27)
#2      genContent (package:assets_gen/src/generator.dart:119:21)
#3      generate (package:assets_gen/src/generator.dart:17:22)
#4      runBuild (file:///home/vishesh/.pub-cache/hosted/pub.dartlang.org/assets_gen-1.3.0/bin/src/build.dart:17:3)
#5      main (file:///home/vishesh/.pub-cache/hosted/pub.dartlang.org/assets_gen-1.3.0/bin/assets_gen.dart:16:5)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
pub finished with exit code 255
```

**Comment by chenenyu** [comment]
try `1.4.0`
